### ISSUE TITLE
Does not work on C64C??

### ISSUE THREAD

**Issue by amigamess** [hackup/MagicDeskCart#1]
Hi, I try to use it on C64C and It seams "not working"...Have you test it on C64C??

Thank you...

**Comment by hackup** [comment]
Thanks for your feedback, but I cannot confirm this. I own two "C64C" and the cartridges I've built (as well as variants thereof) work just fine on those machines. Also, the design has been out there for a while. I have no numbers, but I expect quite a few people will have tried it by now, on different kinds of C64. No one has reported that sort of issue before.

Maybe one of the logic ICs your are using is a bit fishy? Have you tried replacing them with ones from a different source?

**Comment by amigamess** [comment]
Thak you for reply, tested it on C64C and it works fine...Problem is ICs 74ls174p,  .p does not work on C64C...

**Comment by hackup** [comment]
Have you tried multiple 74LS174P from different sources? If not, it is much more likely that just the single IC your were using was faulty. The "P" just denotes the chip package, I think.

Anyway, good to hear that it is working for you now.
